# fly.toml app configuration file generated for design on 2024-12-10T16:05:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'design'
primary_region = 'arn'

[env]
  NODE_ENV = "production"
  
[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
